VIA_ENABLE = yes
VIAL_ENABLE = yes
LTO_ENABLE = yes
NKRO_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes

TAP_DANCE_ENABLE = yes
# KEY_OVERRIDE_ENABLE = yes
COMBO_ENABLE = yes
DYNAMIC_KEYMAP_ENABLE = yes

AUDIO_ENABLE = no
BACKLIGHT_ENABLE = no
RGBLIGHT_ENABLE = no
RGB_MATRIX_ENABLE = no
LED_MATRIX_ENABLE = no
